### ISSUE TITLE
Python （编程）进阶，阅读 The Python Language Reference 之 Simple Statements

### ISSUE THREAD

**Issue by xxleyi** [xxleyi/learning_list#114]
A simple statement is comprised within a single logical line. Several simple statements may occur on a single line separated by semicolons. The syntax for simple statements is:

```
simple_stmt ::=  expression_stmt
                 | assert_stmt
                 | assignment_stmt
                 | augmented_assignment_stmt
                 | annotated_assignment_stmt
                 | pass_stmt
                 | del_stmt
                 | return_stmt
                 | yield_stmt
                 | raise_stmt
                 | break_stmt
                 | continue_stmt
                 | import_stmt
                 | future_stmt
                 | global_stmt
                 | nonlocal_stmt
```

**Comment by xxleyi** [comment]
## 1. Expression statements[](https://docs.python.org/3/reference/simple_stmts.html#expression-statements)

Expression statements are used (mostly interactively) to compute and write a value, or (usually) to call a procedure (a function that returns no meaningful result; in Python, procedures return the value `None`). Other uses of expression statements are allowed and occasionally useful. The syntax for an expression statement is:

`expression_stmt ::=  starred_expression`

An expression statement evaluates the expression list (which may be a single expression).

In interactive mode, if the value is not None, it is converted to a string using the built-in repr() function and the resulting string is written to standard output on a line by itself (except if the result is None, so that procedure calls do not cause any output.)

**Comment by xxleyi** [comment]
## 2. Assignment statements[¶](https://docs.python.org/3/reference/simple_stmts.html#assignment-statements)

**Assignment statements are used to (re)bind names to values and to modify attributes or items of mutable objects**:

```
assignment_stmt ::=  (target_list "=")+ (starred_expression | yield_expression)
target_list     ::=  target ("," target)* [","]
target          ::=  identifier
                     | "(" [target_list] ")"
                     | "[" [target_list] "]"
                     | attributeref
                     | subscription
                     | slicing
                     | "*" target
```

An assignment statement evaluates the expression list (remember that this can be a single expression or a comma-separated list, the latter yielding a tuple) and assigns the single resulting object to each of the target lists, from left to right.

Assignment is defined recursively depending on the form of the target (list). When a target is part of a mutable object (an attribute reference, subscription or slicing), the mutable object must ultimately perform the assignment and decide about its validity, and may raise an exception if the assignment is unacceptable. The rules observed by various types and the exceptions raised are given with the definition of the object types (see section [The standard type hierarchy](https://docs.python.org/3/reference/datamodel.html#types)).

Assignment of an object to a target list, optionally enclosed in parentheses or square brackets, is recursively defined as follows.

  * If the target list is a single target with no trailing comma, optionally in parentheses, the object is assigned to that target.

  * Else: The object must be an iterable with the same number of items as there are targets in the target list, and the items are assigned, from left to right, to the corresponding targets.

    * If the target list contains one target prefixed with an asterisk, called a “starred” target: The object must be an iterable with at least as many items as there are targets in the target list, minus one. The first items of the iterable are assigned, from left to right, to the targets before the starred target. The final items of the iterable are assigned to the targets after the starred target. A list of the remaining items in the iterable is then assigned to the starred target (the list can be empty).

    * Else: The object must be an iterable with the same number of items as there are targets in the target list, and the items are assigned, from left to right, to the corresponding targets.

Assignment of an object to a single target is recursively defined as follows.

  * If the target is an identifier (name):

    * If the name does not occur in a [`global`](https://docs.python.org/3/reference/simple_stmts.html#global) or [`nonlocal`](https://docs.python.org/3/reference/simple_stmts.html#nonlocal) statement in the current code block: the name is bound to the object in the current local namespace.

    * Otherwise: the name is bound to the object in the global namespace or the outer namespace determined by [`nonlocal`](https://docs.python.org/3/reference/simple_stmts.html#nonlocal), respectively.

The name is rebound if it was already bound. This may cause the reference count for the object previously bound to the name to reach zero, causing the object to be deallocated and its destructor (if it has one) to be called.

  * If the target is an attribute reference: The primary expression in the reference is evaluated. It should yield an object with assignable attributes; if this is not the case, [`TypeError`](https://docs.python.org/3/library/exceptions.html#TypeError) is raised. That object is then asked to assign the assigned object to the given attribute; if it cannot perform the assignment, it raises an exception (usually but not necessarily [`AttributeError`](https://docs.python.org/3/library/exceptions.html#AttributeError)).

Note: If the object is a class instance and the attribute reference occurs on both sides of the assignment operator, the RHS expression, `a.x` can access either an instance attribute or (if no instance attribute exists) a class attribute. The LHS target `a.x` is always set as an instance attribute, creating it if necessary. Thus, the two occurrences of `a.x` do not necessarily refer to the same attribute: if the RHS expression refers to a class attribute, the LHS creates a new instance attribute as the target of the assignment:

```
class Cls:
    x = 3             # class variable
inst = Cls()
inst.x = inst.x + 1   # writes inst.x as 4 leaving Cls.x as 3
```

  * This description does not necessarily apply to descriptor attributes, such as properties created with [`property()`](https://docs.python.org/3/library/functions.html#property).

  * If the target is a subscription: The primary expression in the reference is evaluated. It should yield either a mutable sequence object (such as a list) or a mapping object (such as a dictionary). Next, the subscript expression is evaluated.

If the primary is a mutable sequence object (such as a list), the subscript must yield an integer. If it is negative, the sequence’s length is added to it. The resulting value must be a nonnegative integer less than the sequence’s length, and the sequence is asked to assign the assigned object to its item with that index. If the index is out of range, [`IndexError`](https://docs.python.org/3/library/exceptions.html#IndexError) is raised (assignment to a subscripted sequence cannot add new items to a list).

If the primary is a mapping object (such as a dictionary), the subscript must have a type compatible with the mapping’s key type, and the mapping is then asked to create a key/datum pair which maps the subscript to the assigned object. This can either replace an existing key/value pair with the same key value, or insert a new key/value pair (if no key with the same value existed).

For user-defined objects, the [`__setitem__()`](https://docs.python.org/3/reference/datamodel.html#object.__setitem__) method is called with appropriate arguments.

  * **If the target is a slicing**: The primary expression in the reference is evaluated. It should yield a mutable sequence object (such as a list). The assigned object should be a sequence object of the same type. Next, the lower and upper bound expressions are evaluated, insofar they are present; defaults are zero and the sequence’s length. The bounds should evaluate to integers. If either bound is negative, the sequence’s length is added to it. The resulting bounds are clipped to lie between zero and the sequence’s length, inclusive. Finally, the sequence object is asked to replace the slice with the items of the assigned sequence. The length of the slice may be different from the length of the assigned sequence, thus changing the length of the target sequence, if the target sequence allows it.

**CPython implementation detail:** In the current implementation, the syntax for targets is taken to be the same as for expressions, and invalid syntax is rejected during the code generation phase, causing less detailed error messages.

Although the definition of assignment implies that overlaps between the left-hand side and the right-hand side are ‘simultaneous’ (for example `a, b = b, a` swaps two variables), overlaps _within_ the collection of assigned-to variables occur left-to-right, sometimes resulting in confusion. For instance, the following program prints `[0, 2]`:

```python
x = [0, 1]
i = 0
i, x[i] = 1, 2         # i is updated, then x[i] is updated
print(x)
```

```
In [40]: c = dict(a=2, b=3)

In [41]: (_, a), (_, b) = c.items()

In [42]: a
Out[42]: 2

In [43]: b
Out[43]: 3
```

See also

[**PEP 3132**](https://www.python.org/dev/peps/pep-3132) - Extended Iterable Unpacking

     The specification for the `*target` feature.


### 2.1. Augmented assignment statements[](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements)

Augmented assignment is the combination, in a single statement, of a binary operation and an assignment statement:

```
augmented_assignment_stmt ::=  augtarget augop (expression_list | yield_expression)
augtarget                 ::=  identifier | attributeref | subscription | slicing
augop                     ::=  "+=" | "-=" | "*=" | "@=" | "/=" | "//=" | "%=" | "**="
                               | ">>=" | "<<=" | "&=" | "^=" | "|="
```

An augmented assignment evaluates the target (which, unlike normal assignment statements, cannot be an unpacking) and the expression list, performs the binary operation specific to the type of assignment on the two operands, and assigns the result to the original target. The target is only evaluated once.

An augmented assignment expression like `x += 1` can be rewritten as `x = x + 1` to **achieve a similar, but not exactly equal effect**. In the augmented version, `x` is only evaluated once. Also, when possible, the actual operation is performed _in-place_, meaning that rather than creating a new object and assigning that to the target, the old object is modified instead.

Unlike normal assignments, augmented assignments evaluate the left-hand side _before_ evaluating the right-hand side. For example, `a[i] += f(x)` first looks-up `a[i]`, then it evaluates `f(x)` and performs the addition, and lastly, it writes the result back to `a[i]`.

With the exception of assigning to tuples and multiple targets in a single statement, the assignment done by augmented assignment statements is handled the same way as normal assignments. Similarly, with the exception of the possible _in-place_ behavior, the binary operation performed by augmented assignment is the same as the normal binary operations.

For targets which are attribute references, the same [caveat about class and instance attributes](https://docs.python.org/3/reference/simple_stmts.html#attr-target-note) applies as for regular assignments.

### 2.2. Annotated assignment statements[](https://docs.python.org/3/reference/simple_stmts.html#annotated-assignment-statements)

[Annotation](https://docs.python.org/3/glossary.html#term-variable-annotation) assignment is the combination, in a single statement, of a variable or attribute annotation and an optional assignment statement:
    
`annotated_assignment_stmt ::=  augtarget ":" expression ["=" expression]`

The difference from normal [Assignment statements](https://docs.python.org/3/reference/simple_stmts.html#assignment) is that only single target and only single right hand side value is allowed.

For simple names as assignment targets, if in class or module scope, the annotations are evaluated and stored in a special class or module attribute `__annotations__` that is a dictionary mapping from variable names (mangled if private) to evaluated annotations. This attribute is writable and is automatically created at the start of class or module body execution, if annotations are found statically.

For expressions as assignment targets, the annotations are evaluated if in class or module scope, but not stored.

If a name is annotated in a function scope, then this name is local for that scope. Annotations are never evaluated and stored in function scopes.

If the right hand side is present, an annotated assignment performs the actual assignment before evaluating annotations (where applicable). If the right hand side is not present for an expression target, then the interpreter evaluates the target except for the last [`__setitem__()`](https://docs.python.org/3/reference/datamodel.html#object.__setitem__) or [`__setattr__()`](https://docs.python.org/3/reference/datamodel.html#object.__setattr__)call.

See also

> [**PEP 526**](https://www.python.org/dev/peps/pep-0526) - Syntax for Variable Annotations
>     
> 
> The proposal that added syntax for annotating the types of variables (including class variables and instance variables), instead of expressing them through comments.
> 
> [**PEP 484**](https://www.python.org/dev/peps/pep-0484) - Type hints
>     
> 
> The proposal that added the [`typing`](https://docs.python.org/3/library/typing.html#module-typing) module to provide a standard syntax for type annotations that can be used in static analysis tools and IDEs.
>

**Comment by xxleyi** [comment]
## 3. The `assert` statement[](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement)

Assert statements are a convenient way to insert debugging assertions into a program:
    
    `assert_stmt ::= "assert" expression ["," expression] `

The simple form, `assert expression`, is equivalent to
    
    `if __debug__: if not expression: raise AssertionError `

The extended form, `assert expression1, expression2`, is equivalent to
    
    `if __debug__: if not expression1: raise AssertionError(expression2) `

These equivalences assume that [`__debug__`](https://docs.python.org/3/library/constants.html#__debug__) and [`AssertionError`](https://docs.python.org/3/library/exceptions.html#AssertionError) refer to the built-in variables with those names. In the current implementation, the built-in variable [`__debug__`](https://docs.python.org/3/library/constants.html#__debug__) is `True` under normal circumstances, `False` when optimization is requested (command line option [`-O`](https://docs.python.org/3/using/cmdline.html#cmdoption-o)). The current code generator emits no code for an assert statement when optimization is requested at compile time. Note that it is unnecessary to include the source code for the expression that failed in the error message; it will be displayed as part of the stack trace.

Assignments to [`__debug__`](https://docs.python.org/3/library/constants.html#__debug__) are illegal. The value for the built-in variable is determined when the interpreter starts.

**Comment by xxleyi** [comment]
## 4. The `pass` statement[¶](https://docs.python.org/3/reference/simple_stmts.html#the-pass-statement)
    
    pass_stmt ::= "pass" 

[`pass`](https://docs.python.org/3/reference/simple_stmts.html#pass) is a null operation — when it is executed, nothing happens. It is useful as a placeholder when a statement is required syntactically, but no code needs to be executed, for example:
    
    def f(arg): pass # a function that does nothing (yet) 
    class C: pass # a class with no methods (yet)

**Comment by xxleyi** [comment]
## 5. The `del` statement[](https://docs.python.org/3/reference/simple_stmts.html#the-del-statement)
    
    del_stmt ::= "del" target_list

Deletion is recursively defined very similar to the way assignment is defined. Rather than spelling it out in full details, here are some hints.

Deletion of a target list recursively deletes each target, from left to right.

Deletion of a name removes the binding of that name from the local or global namespace, depending on whether the name occurs in a [`global`](https://docs.python.org/3/reference/simple_stmts.html#global) statement in the same code block. If the name is unbound, a [`NameError`](https://docs.python.org/3/library/exceptions.html#NameError) exception will be raised.

Deletion of attribute references, subscriptions and slicings is passed to the primary object involved; deletion of a slicing is in general equivalent to assignment of an empty slice of the right type (but even this is determined by the sliced object).

Changed in version 3.2: Previously it was illegal to delete a name from the local namespace if it occurs as a free variable in a nested block.

**Comment by xxleyi** [comment]
## 6. The `return` statement[¶](https://docs.python.org/3/reference/simple_stmts.html#the-return-statement)
    
    **return_stmt** ::= "return" [expression_list]

[`return`](https://docs.python.org/3/reference/simple_stmts.html#return) may only occur syntactically nested in a function definition, not within a nested class definition.

If an expression list is present, it is evaluated, else `None` is substituted.

[`return`](https://docs.python.org/3/reference/simple_stmts.html#return) leaves the current function call with the expression list (or `None`) as return value.

When [`return`](https://docs.python.org/3/reference/simple_stmts.html#return) passes control out of a [`try`](https://docs.python.org/3/reference/compound_stmts.html#try) statement with a [`finally`](https://docs.python.org/3/reference/compound_stmts.html#finally) clause, that `finally` clause is executed before really leaving the function.

In a generator function, the [`return`](https://docs.python.org/3/reference/simple_stmts.html#return) statement indicates that the generator is done and will cause [`StopIteration`](https://docs.python.org/3/library/exceptions.html#StopIteration) to be raised. The returned value (if any) is used as an argument to construct [`StopIteration`](https://docs.python.org/3/library/exceptions.html#StopIteration) and becomes the `StopIteration.value` attribute.

In an asynchronous generator function, an empty [`return`](https://docs.python.org/3/reference/simple_stmts.html#return) statement indicates that the asynchronous generator is done and will cause [`StopAsyncIteration`](https://docs.python.org/3/library/exceptions.html#StopAsyncIteration) to be raised. A non-empty `return` statement is a syntax error in an asynchronous generator function.

**Comment by xxleyi** [comment]
## 7. The `yield` statement[¶](https://docs.python.org/3/reference/simple_stmts.html#the-yield-statement)
    
    yield_stmt ::= yield_expression

A [`yield`](https://docs.python.org/3/reference/simple_stmts.html#yield) statement is semantically equivalent to a [yield expression](https://docs.python.org/3/reference/expressions.html#yieldexpr). The yield statement can be used to omit the parentheses that would otherwise be required in the equivalent yield expression statement. For example, the yield statements
    
    yield <expr> yield from <expr> 

are equivalent to the yield expression statements
    
    (yield <expr>) 
    (yield from <expr>) 

Yield expressions and statements are only used when defining a [generator](https://docs.python.org/3/glossary.html#term-generator) function, and are only used in the body of the generator function. Using yield in a function definition is sufficient to cause that definition to create a generator function instead of a normal function.

For full details of [`yield`](https://docs.python.org/3/reference/simple_stmts.html#yield) semantics, refer to the [Yield expressions](https://docs.python.org/3/reference/expressions.html#yieldexpr) section.

**Comment by xxleyi** [comment]
## 8. The `raise` statement[¶](https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement)
    
    raise_stmt ::=  "raise" [expression ["from" expression]]

If no expressions are present, [`raise`](https://docs.python.org/3/reference/simple_stmts.html#raise) re-raises the last exception that was active in the current scope. If no exception is active in the current scope, a [`RuntimeError`](https://docs.python.org/3/library/exceptions.html#RuntimeError) exception is raised indicating that this is an error.

Otherwise, [`raise`](https://docs.python.org/3/reference/simple_stmts.html#raise) evaluates the first expression as the exception object. It must be either a subclass or an instance of [`BaseException`](https://docs.python.org/3/library/exceptions.html#BaseException). If it is a class, the exception instance will be obtained when needed by instantiating the class with no arguments.

The _type_ of the exception is the exception instance’s class, the _value_ is the instance itself.

A traceback object is normally created automatically when an exception is raised and attached to it as the `__traceback__` attribute, which is writable. You can create an exception and set your own traceback in one step using the `with_traceback()` exception method (which returns the same exception instance, with its traceback set to its argument), like so:
    
    raise Exception("foo occurred").with_traceback(tracebackobj) 

The `from` clause is used for exception chaining: if given, the second _expression_ must be another exception class or instance, which will then be attached to the raised exception as the `__cause__`attribute (which is writable). If the raised exception is not handled, both exceptions will be printed:
    
```
>>> try:
...     print(1 / 0)
... except Exception as exc:
...     raise RuntimeError("Something bad happened") from exc
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
RuntimeError: Something bad happened
```

A similar mechanism works implicitly if an exception is raised inside an exception handler or a [`finally`](https://docs.python.org/3/reference/compound_stmts.html#finally) clause: the previous exception is then attached as the new exception’s `__context__`attribute:

```
>>> try:
...     print(1 / 0)
... except Exception as exc:
...     raise RuntimeError("Something bad happened") from exc
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
RuntimeError: Something bad happened
```

Exception chaining can be explicitly suppressed by specifying [`None`](https://docs.python.org/3/library/constants.html#None) in the `from` clause:

```
>>> try:
...     print(1 / 0)
... except:
...     raise RuntimeError("Something bad happened") from None
...
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
RuntimeError: Something bad happened
```

Additional information on exceptions can be found in section [Exceptions](https://docs.python.org/3/reference/executionmodel.html#exceptions), and information about handling exceptions is in section [The try statement](https://docs.python.org/3/reference/compound_stmts.html#try).

Changed in version 3.3: [`None`](https://docs.python.org/3/library/constants.html#None) is now permitted as `Y` in `raise X from Y`.

New in version 3.3: The `__suppress_context__` attribute to suppress automatic display of the exception context.

**Comment by xxleyi** [comment]
## 9. The `break` statement[¶](https://docs.python.org/3/reference/simple_stmts.html#the-break-statement)
    
    break_stmt ::= "break" 

[`break`](https://docs.python.org/3/reference/simple_stmts.html#break) may only occur syntactically nested in a [`for`](https://docs.python.org/3/reference/compound_stmts.html#for) or [`while`](https://docs.python.org/3/reference/compound_stmts.html#while) loop, but not nested in a function or class definition within that loop.

It terminates the nearest enclosing loop, skipping the optional `else` clause if the loop has one.

If a [`for`](https://docs.python.org/3/reference/compound_stmts.html#for) loop is terminated by [`break`](https://docs.python.org/3/reference/simple_stmts.html#break), the loop control target keeps its current value.

When [`break`](https://docs.python.org/3/reference/simple_stmts.html#break) passes control out of a [`try`](https://docs.python.org/3/reference/compound_stmts.html#try) statement with a [`finally`](https://docs.python.org/3/reference/compound_stmts.html#finally) clause, that `finally` clause is executed before really leaving the loop.

## 10. The `continue` statement[](https://docs.python.org/3/reference/simple_stmts.html#the-continue-statement)
    
    continue_stmt ::= "continue" 

[`continue`](https://docs.python.org/3/reference/simple_stmts.html#continue) may only occur syntactically nested in a [`for`](https://docs.python.org/3/reference/compound_stmts.html#for) or [`while`](https://docs.python.org/3/reference/compound_stmts.html#while) loop, but not nested in a function or class definition or [`finally`](https://docs.python.org/3/reference/compound_stmts.html#finally) clause within that loop. It continues with the next cycle of the nearest enclosing loop.

When [`continue`](https://docs.python.org/3/reference/simple_stmts.html#continue) passes control out of a [`try`](https://docs.python.org/3/reference/compound_stmts.html#try) statement with a [`finally`](https://docs.python.org/3/reference/compound_stmts.html#finally) clause, that `finally` clause is executed before really starting the next loop cycle.

**Comment by xxleyi** [comment]
## 11. The `import` statement[¶](https://docs.python.org/3/reference/simple_stmts.html#the-import-statement)

```
import_stmt     ::=  "import" module ["as" identifier] ("," module ["as" identifier])*
                     | "from" relative_module "import" identifier ["as" identifier]
                     ("," identifier ["as" identifier])*
                     | "from" relative_module "import" "(" identifier ["as" identifier]
                     ("," identifier ["as" identifier])* [","] ")"
                     | "from" module "import" "*"
module          ::=  (identifier ".")* identifier
relative_module ::=  "."* module | "."+
```

The basic import statement (no [`from`](https://docs.python.org/3/reference/simple_stmts.html#from) clause) is executed in two steps:

  1. find a module, loading and initializing it if necessary

  2. define a name or names in the local namespace for the scope where the [`import`](https://docs.python.org/3/reference/simple_stmts.html#import) statement occurs.

When the statement contains multiple clauses (separated by commas) the two steps are carried out separately for each clause, just as though the clauses had been separated out into individual import statements.

The details of the first step, finding and loading modules are described in greater detail in the section on the [import system](https://docs.python.org/3/reference/import.html#importsystem), which also describes the various types of packages and modules that can be imported, as well as all the hooks that can be used to customize the import system. Note that failures in this step may indicate either that the module could not be located, _or_ that an error occurred while initializing the module, which includes execution of the module’s code.

If the requested module is retrieved successfully, it will be made available in the local namespace in one of three ways:

  * If the module name is followed by `as`, then the name following `as` is bound directly to the imported module.

  * If no other name is specified, and the module being imported is a top level module, the module’s name is bound in the local namespace as a reference to the imported module

  * If the module being imported is _not_ a top level module, then the name of the top level package that contains the module is bound in the local namespace as a reference to the top level package. The imported module must be accessed using its full qualified name rather than directly

The [`from`](https://docs.python.org/3/reference/simple_stmts.html#from) form uses a slightly more complex process:

  1. find the module specified in the [`from`](https://docs.python.org/3/reference/simple_stmts.html#from) clause, loading and initializing it if necessary;

  2. for each of the identifiers specified in the [`import`](https://docs.python.org/3/reference/simple_stmts.html#import) clauses:
    1. check if the imported module has an attribute by that name

    2. if not, attempt to import a submodule with that name and then check the imported module again for that attribute

    3. if the attribute is not found, [`ImportError`](https://docs.python.org/3/library/exceptions.html#ImportError) is raised.

    4. otherwise, a reference to that value is stored in the local namespace, using the name in the `as` clause if it is present, otherwise using the attribute name

Examples:
    
    import foo # foo imported and bound locally 
    import foo.bar.baz # foo.bar.baz imported, foo bound locally 
    import foo.bar.baz as fbb # foo.bar.baz imported and bound as fbb 
    from foo.bar import baz # foo.bar.baz imported and bound as baz 
    from foo import attr # foo imported and foo.attr bound as attr 

If the list of identifiers is replaced by a star (`'*'`), all public names defined in the module are bound in the local namespace for the scope where the [`import`](https://docs.python.org/3/reference/simple_stmts.html#import) statement occurs.

The _public names_ defined by a module are determined by checking the module’s namespace for a variable named `__all__`; if defined, it must be a sequence of strings which are names defined or imported by that module. The names given in `__all__` are all considered public and are required to exist. If `__all__` is not defined, the set of public names includes all names found in the module’s namespace which do not begin with an underscore character (`'_'`). `__all__` should contain the entire public API. It is intended to avoid accidentally exporting items that are not part of the API (such as library modules which were imported and used within the module).

The wild card form of import — `from module import *` — is only allowed at the module level. Attempting to use it in class or function definitions will raise a [`SyntaxError`](https://docs.python.org/3/library/exceptions.html#SyntaxError).

When specifying what module to import you do not have to specify the absolute name of the module. When a module or package is contained within another package it is possible to make a relative import within the same top package without having to mention the package name. By using leading dots in the specified module or package after [`from`](https://docs.python.org/3/reference/simple_stmts.html#from) you can specify how high to traverse up the current package hierarchy without specifying exact names. One leading dot means the current package where the module making the import exists. Two dots means up one package level. Three dots is up two levels, etc. So if you execute `from . import mod` from a module in the `pkg` package then you will end up importing `pkg.mod`. If you execute `from ..subpkg2 import mod` from within `pkg.subpkg1` you will import `pkg.subpkg2.mod`. The specification for relative imports is contained in the [Package Relative Imports](https://docs.python.org/3/reference/import.html#relativeimports) section.

[`importlib.import_module()`](https://docs.python.org/3/library/importlib.html#importlib.import_module) is provided to support applications that determine dynamically the modules to be loaded.

**Comment by xxleyi** [comment]
### 11.1. Future statements[](https://docs.python.org/3/reference/simple_stmts.html#future-statements)

A _future statement_ is a directive to the compiler that a particular module should be compiled using syntax or semantics that will be available in a specified future release of Python where the feature becomes standard.

The future statement is intended to ease migration to future versions of Python that introduce incompatible changes to the language. It allows use of the new features on a per-module basis before the release in which the feature becomes standard.
    
```
future_stmt ::=  "from" "__future__" "import" feature ["as" identifier]
                 ("," feature ["as" identifier])*
                 | "from" "__future__" "import" "(" feature ["as" identifier]
                 ("," feature ["as" identifier])* [","] ")"
feature     ::=  identifier
```

A future statement must appear near the top of the module. The only lines that can appear before a future statement are:

  * the module docstring (if any),

  * comments,

  * blank lines, and

  * other future statements.

The only feature in Python 3.7 that requires using the future statement is `annotations`.

All historical features enabled by the future statement are still recognized by Python 3. The list includes `absolute_import`, `division`, `generators`, `generator_stop`, `unicode_literals`,`print_function`, `nested_scopes` and `with_statement`. They are all redundant because they are always enabled, and only kept for backwards compatibility.

A future statement is recognized and treated specially at compile time: Changes to the semantics of core constructs are often implemented by generating different code. It may even be the case that a new feature introduces new incompatible syntax (such as a new reserved word), in which case the compiler may need to parse the module differently. Such decisions cannot be pushed off until runtime.

For any given release, the compiler knows which feature names have been defined, and raises a compile-time error if a future statement contains a feature not known to it.

The direct runtime semantics are the same as for any import statement: there is a standard module [`__future__`](https://docs.python.org/3/library/__future__.html#module-__future__), described later, and it will be imported in the usual way at the time the future statement is executed.

The interesting runtime semantics depend on the specific feature enabled by the future statement.

Note that there is nothing special about the statement:
    
    import __future__ [as name] 

That is not a future statement; it’s an ordinary import statement with no special semantics or syntax restrictions.

Code compiled by calls to the built-in functions [`exec()`](https://docs.python.org/3/library/functions.html#exec) and [`compile()`](https://docs.python.org/3/library/functions.html#compile) that occur in a module `M`containing a future statement will, by default, use the new syntax or semantics associated with the future statement. This can be controlled by optional arguments to [`compile()`](https://docs.python.org/3/library/functions.html#compile) — see the documentation of that function for details.

A future statement typed at an interactive interpreter prompt will take effect for the rest of the interpreter session. If an interpreter is started with the [`-i`](https://docs.python.org/3/using/cmdline.html#cmdoption-i) option, is passed a script name to execute, and the script includes a future statement, it will be in effect in the interactive session started after the script is executed.

See also

> [**PEP 236**](https://www.python.org/dev/peps/pep-0236) - Back to the __future__
>     
> The original proposal for the __future__ mechanism.
>

**Comment by xxleyi** [comment]
## 12. The `global` statement[](https://docs.python.org/3/reference/simple_stmts.html#the-global-statement)
    
    **global_stmt** ::= "global" [identifier](https://docs.python.org/3/reference/lexical_analysis.html#grammar-token-identifier) ("," [identifier](https://docs.python.org/3/reference/lexical_analysis.html#grammar-token-identifier))* 

The [`global`](https://docs.python.org/3/reference/simple_stmts.html#global) statement is a declaration which holds for the entire current code block. It means that the listed identifiers are to be interpreted as globals. It would be impossible to assign to a global variable without `global`, although free variables may refer to globals without being declared global.

Names listed in a [`global`](https://docs.python.org/3/reference/simple_stmts.html#global) statement must not be used in the same code block textually preceding that `global` statement.

Names listed in a [`global`](https://docs.python.org/3/reference/simple_stmts.html#global) statement must not be defined as formal parameters or in a [`for`](https://docs.python.org/3/reference/compound_stmts.html#for) loop control target, [`class`](https://docs.python.org/3/reference/compound_stmts.html#class) definition, function definition, [`import`](https://docs.python.org/3/reference/simple_stmts.html#import) statement, or variable annotation.

**CPython implementation detail:** The current implementation does not enforce some of these restrictions, but programs should not abuse this freedom, as future implementations may enforce them or silently change the meaning of the program.

**Programmer’s note:** [`global`](https://docs.python.org/3/reference/simple_stmts.html#global) is a directive to the parser. It applies only to code parsed at the same time as the `global` statement. In particular, a `global` statement contained in a string or code object supplied to the built-in [`exec()`](https://docs.python.org/3/library/functions.html#exec) function does not affect the code block _containing_ the function call, and code contained in such a string is unaffected by `global` statements in the code containing the function call. The same applies to the [`eval()`](https://docs.python.org/3/library/functions.html#eval) and [`compile()`](https://docs.python.org/3/library/functions.html#compile) functions.

## 13. The `nonlocal` statement[](https://docs.python.org/3/reference/simple_stmts.html#the-nonlocal-statement)
    
    **nonlocal_stmt** ::= "nonlocal" [identifier](https://docs.python.org/3/reference/lexical_analysis.html#grammar-token-identifier) ("," [identifier](https://docs.python.org/3/reference/lexical_analysis.html#grammar-token-identifier))* 

The [`nonlocal`](https://docs.python.org/3/reference/simple_stmts.html#nonlocal) statement causes the listed identifiers to refer to previously bound variables in the nearest enclosing scope excluding globals. This is important because the default behavior for binding is to search the local namespace first. The statement allows encapsulated code to rebind variables outside of the local scope besides the global (module) scope.

Names listed in a [`nonlocal`](https://docs.python.org/3/reference/simple_stmts.html#nonlocal) statement, unlike those listed in a [`global`](https://docs.python.org/3/reference/simple_stmts.html#global) statement, must refer to pre-existing bindings in an enclosing scope (the scope in which a new binding should be created cannot be determined unambiguously).

Names listed in a [`nonlocal`](https://docs.python.org/3/reference/simple_stmts.html#nonlocal) statement must not collide with pre-existing bindings in the local scope.

See also

[**PEP 3104**](https://www.python.org/dev/peps/pep-3104) - Access to Names in Outer Scopes
    

The specification for the [`nonlocal`](https://docs.python.org/3/reference/simple_stmts.html#nonlocal) statement.

**Comment by xxleyi** [comment]
捋了捋 Simple Statements，收获挺大，干掉了几个死角：

- 析构表达式
- 析构赋值
- 交换赋值并不是同步
- break, continue 在循环体内，但不能在循环体内的函数或者类的定义中
- return, break, continue 不影响 finally 的运行
- `__debug__ 变量结合 assert 使用`
